language: node_js
node_js:
  - 10

addons:
  chrome: stable

os: linux
dist: trusty

cache:
  npm: true

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run test:node
  - npm run test:browser

